resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/25.yaml

packages:
- tree
- tree-cli
- tree-view

extra-deps:
- gloss-1.13.2.1@sha256:273d02d30e1896932d45424dab6022a16986c0ed3eef6937776b5f40854ce51c,4075
- haskeline-0.8.2@sha256:3a80aff4c751b475337ace00ac5757c5d47a47de94954fb87cce168a90e19c7a,6005

flags: {}

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

ghc-options:
  '$everything': -haddock